version: '3.1'

services:

  wordpress_db:
    container_name: wordpress_db
    image: mariadb:latest
    restart: always
    volumes:
      - avartandb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME} 
      MYSQL_USER: ${MYSQL_ROOT_USER} 
      MYSQL_PASSWORD: ${MYSQL_DATABASE_USER_PASSWORD} 
    ports:
      - "${PORT_MYSQL}:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
        - wordpress_db:db
    ports:
        - "${PORT_PHPMYADMIN}:80"
    environment:
      MYSQL_USERNAME: ${MYSQL_ROOT_USER} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      PMA_HOST: wordpress_db

  wordpress:
    depends_on:
      - wordpress_db
    build: ./wordpress
    container_name: wordpress
    ports:
      - "${PORT_WORDPRESS}:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content/
      - ./wordpress/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

    restart: unless-stopped
    environment:
       WORDPRESS_DEBUG: 0
       WORDPRESS_DB_NAME: ${MYSQL_DATABASE_NAME} 
       WORDPRESS_DB_HOST: wordpress_db:3306
       WORDPRESS_DB_USER: ${MYSQL_ROOT_USER} 
       WORDPRESS_DB_PASSWORD: ${MYSQL_DATABASE_USER_PASSWORD} 


volumes:
  avartandb:


